var ships = {
    LightCargo:{
        id: 202,
        structure: 4000,
        shield: 10,
        attack: 5,
        rhenium: 2000,
        selenium: 2000,
        nitrogen: 0,
        name:{
            EN: 'Light Cargo',
            FR: 'Transporteur Léger',
        },
        capacity: 1200,
        baseSpeed: 10000,
        propulsion: "impulsion",
        consumption: 20
    },
    HeavyCargo:{
        id: 203,
        structure: 12000,
        shield: 30,
        attack: 15,
        rhenium: 6000,
        selenium: 6000,
        nitrogen: 0,
        name:{
            EN: 'Heavy Cargo',
            FR: 'Transporteur Lourd',
        },
        capacity: 35000,
        baseSpeed: 7500,
        propulsion: "combustion",
        consumption: 50,
    },
    MercuryBigShipCargo:{
        id: 229,
        structure: 45000,
        shield: 115,
        attack: 40,
        rhenium: 25000,
        selenium: 20000,
        nitrogen: 1500,
        name:{
            EN: 'Mercury Big Ship Cargo',
            FR: 'Cargo Planétaire',
        },
        capacity: 100000,
        baseSpeed: 12500,
        propulsion: "impulsion",
        consumption: 125,
    },
    ColonyShip:{
        id: 208,
        structure: 30000,
        shield: 100,
        attack: 50,
        rhenium: 10000,
        selenium: 20000,
        nitrogen: 10000,
        name:{
            EN: 'Colony Ship',
            FR: 'Colonisateur',
        },
        capacity: 7500,
        baseSpeed: 2500,
        propulsion: "impulsion",
        consumption: 1000,
    },
    Recycler:{
        id: 209,
        structure: 16000,
        shield: 45,
        attack: 1,
        rhenium: 10000,
        selenium: 6000,
        nitrogen: 2000,
        name:{
            EN: 'Recycler',
            FR: 'Recycleur',
        },
        capacity: 25000,
        baseSpeed: 2000,
        propulsion: "combustion",
        consumption: 150,
    },
    GigaRecycler:{
        id: 219,
        structure: 160000,
        shield: 475,
        attack: 1,
        rhenium: 100000,
        selenium: 60000,
        nitrogen: 20000,
        name:{
            EN: 'Giga Recycler',
            FR: 'Recycleur Ultime',
        },
        capacity: 275000,
        baseSpeed: 2500,
        propulsion: "inertia",
        consumption: 300,
    },
    Extractor:{
        id: 225,
        structure: 100000,
        shield: 325,
        attack: 1,
        rhenium: 50000,
        selenium: 50000,
        nitrogen: 25000,
        name:{
            EN: 'Extractor',
            FR: 'Extracteur',
        },
        capacity: 10000,
        baseSpeed: 500,
        propulsion: "impulsion",
        consumption: 150,
    }
};

